name: The Retro Toys
favicon: null
layout_spectrum: 0.401954312575981
typography_spectrum: 0.17108670459128916
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7108131502754986
  lightness: 0.7741490255575627
  saturation: 0.9290141894016415
  rhythmicContrast: 0.09837615094147623
purpose: []
